/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WashRouteImport } from './routes/wash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SewingRouteImport } from './routes/sewing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QcRouteImport } from './routes/qc'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuttingRouteImport } from './routes/cutting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'

const WashRoute = WashRouteImport.update({
  id: '/wash',
  path: '/wash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SewingRoute = SewingRouteImport.update({
  id: '/sewing',
  path: '/sewing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuttingRoute = CuttingRouteImport.update({
  id: '/cutting',
  path: '/cutting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sewing': typeof SewingRoute
  '/signup': typeof SignupRoute
  '/wash': typeof WashRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sewing': typeof SewingRoute
  '/signup': typeof SignupRoute
  '/wash': typeof WashRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sewing': typeof SewingRoute
  '/signup': typeof SignupRoute
  '/wash': typeof WashRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/login'
    | '/materials'
    | '/orders'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/signup'
    | '/wash'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/login'
    | '/materials'
    | '/orders'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/signup'
    | '/wash'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/login'
    | '/materials'
    | '/orders'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/signup'
    | '/wash'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuttingRoute: typeof CuttingRoute
  DashboardRoute: typeof DashboardRoute
  DispatchRoute: typeof DispatchRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  QcRoute: typeof QcRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SewingRoute: typeof SewingRoute
  SignupRoute: typeof SignupRoute
  WashRoute: typeof WashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wash': {
      id: '/wash'
      path: '/wash'
      fullPath: '/wash'
      preLoaderRoute: typeof WashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewing': {
      id: '/sewing'
      path: '/sewing'
      fullPath: '/sewing'
      preLoaderRoute: typeof SewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutting': {
      id: '/cutting'
      path: '/cutting'
      fullPath: '/cutting'
      preLoaderRoute: typeof CuttingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuttingRoute: CuttingRoute,
  DashboardRoute: DashboardRoute,
  DispatchRoute: DispatchRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  QcRoute: QcRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SewingRoute: SewingRoute,
  SignupRoute: SignupRoute,
  WashRoute: WashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
